In [30]:
import numpy as np
import csv

cd = os.path.dirname(os.path.realpath('__file__'))

In [42]:
synthetic1_train = np.genfromtxt("../data/synthetic1_train.csv", delimiter=",", skip_header=1)

In [66]:
print(synthetic1_train, synthetic1_train.shape)

[[-7.6615e+00 -5.7644e+00  1.0000e+00]
 [-5.1141e-01  1.9586e+00  1.0000e+00]
 [ 2.3214e+00  5.0545e+00  1.0000e+00]
 [-2.0195e+00  3.4092e-01  1.0000e+00]
 [-2.9861e+00 -3.3190e+00  1.0000e+00]
 [-6.5189e+00 -4.7777e+00  1.0000e+00]
 [ 2.6641e-01  2.3592e+00  1.0000e+00]
 [-4.8785e+00 -3.5146e+00  1.0000e+00]
 [-4.8374e+00 -2.8104e+00  1.0000e+00]
 [ 7.0224e-01  3.3218e+00  1.0000e+00]
 [ 5.7500e+00  6.9757e+00  1.0000e+00]
 [-6.8286e+00 -5.7670e+00  1.0000e+00]
 [-1.7667e+00 -5.6320e-01  1.0000e+00]
 [ 4.0435e-01  1.8636e+00  1.0000e+00]
 [-1.5761e+00 -6.3041e-01  1.0000e+00]
 [ 2.1320e+00  5.0140e+00  1.0000e+00]
 [-5.1850e+00 -3.5251e+00  1.0000e+00]
 [ 3.2005e+00  2.3888e+00  1.0000e+00]
 [-5.9964e-01  1.9578e+00  1.0000e+00]
 [-1.5437e+00  3.2573e-01  1.0000e+00]
 [-7.8170e+00 -5.1727e+00  1.0000e+00]
 [-3.6526e+00 -3.2991e+00  1.0000e+00]
 [-7.0529e-01  5.0600e-03  1.0000e+00]
 [-3.0048e+00 -6.8425e-01  1.0000e+00]
 [-2.3935e+00 -1.9034e+00  1.0000e+00]
 [-9.4264e-01 -4.6249e-01

In [65]:
synthetic1_train[:,0]

array([-7.6615  , -0.51141 ,  2.3214  , -2.0195  , -2.9861  , -6.5189  ,
        0.26641 , -4.8785  , -4.8374  ,  0.70224 ,  5.75    , -6.8286  ,
       -1.7667  ,  0.40435 , -1.5761  ,  2.132   , -5.185   ,  3.2005  ,
       -0.59964 , -1.5437  , -7.817   , -3.6526  , -0.70529 , -3.0048  ,
       -2.3935  , -0.94264 , -1.9343  , -1.283   , -0.38848 , -1.1151  ,
       -1.709   ,  1.9344  , -4.299   , -5.9648  , -4.1375  , -4.0518  ,
        3.9041  , -7.0233  , -1.1953  , -1.2685  ,  0.13147 , -6.8244  ,
        4.198   , -3.3886  ,  1.3651  , -5.7778  ,  7.568   , -3.9977  ,
       -8.2418  , -1.0683  ,  5.4001  ,  5.1599  ,  3.0834  ,  4.1844  ,
        0.39144 ,  4.4168  ,  6.223   ,  1.2892  ,  8.6351  ,  1.8482  ,
       -0.87547 , -0.42572 , -0.9233  , -0.081171,  1.0514  ,  6.3585  ,
        2.7006  , -0.75879 ,  5.1726  ,  2.2665  ,  0.7177  ,  8.0069  ,
        1.0234  ,  4.8224  ,  1.5403  ,  6.2164  ,  6.6096  ,  3.1687  ,
        4.238   , -0.11387 ,  2.0702  ,  2.385   , 

In [3]:
import os
print(os.getcwd())

D:\GDriveUSC\EE559_ML\ML1-class\nearest-mean-classifier\notebook
